db:
  container_name: <%= projectName %>_local_db
  image: phase2/mariadb
  environment:
    DNSDOCK_NAME: db
    DNSDOCK_IMAGE: <%= domain %>
    MYSQL_DATABASE: <%= machineName %>_drupal
  volumes:
    - /data/<%= projectName %>_local/mysql:/var/lib/mysql
<% if (cache.external) { %>
<%- include cache.partial.yml -%>
<% } %>
www:
  container_name: <%= projectName %>_local_www
  image: <%= app.image %>
  environment:
    DNSDOCK_NAME: www
    DNSDOCK_IMAGE: <%= domain %>
    DOCROOT: /var/www/build/html
    PHP_XDEBUG: "<%= debugMode %>"
    PHP_XHPROF: "<%= debugMode %>"
  links:
    - db<% if (cache.external) { %><%= cache.docker.link %><% } %>
  volumes:
    - .:/var/www/
    - /data/<%= projectName %>_local/files:/var/www/build/html/sites/default/files
