db:
  extends:
    file: docker-compose.yml
    service: db
<% if (cacheInternal) { %>
cache:
  extends:
    file: docker-compose.yml
    service: cache
<% } %>
www:
  environment:
    PHP_XDEBUG: "<%= debugMode %>"
    PHP_XHPROF: "<%= debugMode %>"
    VIRTUAL_HOST: <%= virtualHost %>
  extends:
    file: docker-compose.yml
    service: www
