version: "2.1"

services:

  # Opens the container with a BASH session and sets the working directory to
  # the local of the volume-mounted generator code.
  cli:
    extends:
      service: yo
    working_dir: /usr/local/lib/node_modules/generator-outrigger-drupal
    entrypoint: ["/usr/bin/env"]
    command: "bash"

  # Runs the primary yo generator with node-inspector debugging activated.
  # Usage: docker-compose run --rm debug
  debug:
    extends:
      service: yo
    entrypoint: "/usr/local/lib/node_modules/generator-outrigger-drupal/bin/debug 'outrigger-drupal --no-insight --skip-install'"
    ports:
      - "8080"
    labels:
      com.dnsdock.image: yo
      com.dnsdock.name: debug

  # Run 'yo' inside the container.
  # Usage: docker-compose run --rm yo
  # docker-compose run --rm yo outrigger-drupal
  # docker-compose run --rm yo outrigger-drupal:environment
  # docker-compose run --rm yo outrigger-drupal:jenkins
  yo:
    image: outrigger/yeoman
    network_mode: "bridge"
    volumes:
      - ${YO_PROJECT_DIRECTORY:-~/Projects/newproject}:/generated
      - .:/usr/local/lib/node_modules/generator-outrigger-drupal
