##
# Operational services to run the application in DevCloud-hosted Docker environments.
#
# In-line documentation assumes the "Integration" or 'int' environment, in practice
# any environment name can be used. Standard names also include: Development (dev),
# Testing (qa), and Review/Milestone (review).
#
# "Dev Cloud" is the name of the internal Phase2 development infrastructure.
#
# To ensure this works as expected for multiple environments, both environment
# settings must be carefully respected in *every* command invocation:
#
# * The `DOCKER_ENV` environment variable which is used as a template parameter for
#   how this configuration is used.
# * The -p|--project-name option for Docker Compose, which used the provided name
#   in lieu of deriving key Docker namespacing from whatever the current directory
#   happens to be named.
#
# Common Operations
#
# * Start all services in the background: `DOCKER_ENV=int docker-compose up -d`
# * Connect to a container to run limited commands: `docker exec -it <container_name> bash`
##
version: '2.1'

services:
  # Database service
  db:
    extends:
      file: docker-compose.yml
      service: db
  <% if (cache.external) { %>
  # Application Cache service
  cache:
    extends:
      file: docker-compose.yml
      service: cache
  <% } %><% if (proxy.exists) { %>
  # Reverse-proxy Cache service
  proxy:
    extends:
      file: docker-compose.yml
      service: proxy
    environment:
      VIRTUAL_HOST: ${DOCKER_ENV}-<%= host.devcloud %>
    links:
      - www
  <% } if (mail.exists) { %>
  # MailHog SMTP and UI service.
  mail:
    extends:
      file: docker-compose.yml
      service: mail
    environment:
      VIRTUAL_HOST: mail-${DOCKER_ENV}-<%= host.devcloud %>
      VIRTUAL_PORT: '8025'
  <% } %>
  # Main Application service.
  www:
    extends:
      file: docker-compose.yml
      service: www
    environment:
      PHP_XDEBUG: "<%= debugMode %>"
      PHP_XHPROF: "<%= debugMode %>"
      <% if (!proxy.exists) { %>VIRTUAL_HOST: ${DOCKER_ENV}-<%= host.devcloud %><% } %>
    links:
      - db<% if (cache.external) { %><%= cache.docker.link %><% } %><% if (mail.exists) { %><%= mail.docker.link %><% } %>
