##
# Build and command-line operations containers for your local environment.
##

# Container for starting a cli for build commands
# Usage: docker-compose -f build.yml run cli
cli:
  extends:
    service: operational

# Container for running drush in the docroot.
# Usage: docker-compose -f build.yml run drush <command>
# Where <command> is a direct drush command like cache-rebuild
drush:
  extends:
    service: operational
  entrypoint: [ "/init", "drush", "@<%= projectName %>" ]
  working_dir: /var/www/build/html

# Container for running grunt in the docroot.
# Usage: docker-compose -f build.yml run grunt <command>
grunt:
  extends:
    service: operational
  entrypoint: [ "/init", "grunt" ]

# Operational base service definition for Local environment.
#
# Unlike `base`, this layer is functional for application interactions.
#
# Other services inherit these settings via the extends property.
# See https://docs.docker.com/compose/extends/#extending-services
operational:
  extends:
    service: base
  external_links:
    - <%= db.docker.extLink %><% if (cache.external) { %><%= cache.docker.extLink %><% } %>

# Base service definition for Local environment.
#
# This is not a fully operational build container, lacking access to other
# services such as the database or cache needed to properly interact with the
# application.
#
# Uses for this container include filesystem operations. For example:
#
# docker-compose -f build.yml run base 'rm -Rf node_modules'
#
# Other services inherit these settings via the extends property.
# See https://docs.docker.com/compose/extends/#extending-services
base:
  image: phase2/devtools-build:php56
  entrypoint: [ "/init" ]
  working_dir: /var/www
  command: /bin/bash
  volumes:
    - .:/var/www/
    - ./env/build/etc/drush:/root/.drush
    - ./build/backups:/opt/backups
    - /data/<%= projectName %>_local/cache/drush:/root/.drush/cache
    - /data/<%= projectName %>_local/cache/composer:/root/.composer/cache
    - /data/<%= projectName %>_local/cache/npm:/root/.npm
    - /data/<%= projectName %>_local/cache/bower:/root/.cache/bower
    - /data/<%= projectName %>_local/cache/fontconfig:/root/.cache/fontconfig
  environment:
    APP_DOMAIN: <%= host.local %>
    GDT_DOMAIN: <%= host.local %>
    <% if (proxy.exists) { %>PROXY_VIRTUAL_HOST: <%= host.local %><% } %>
