db:
  container_name: <%= projectName %>_local_db
  image: phase2/mariadb
  environment:
    DNSDOCK_NAME: db
    DNSDOCK_IMAGE: <%= projectName %>
    MYSQL_DATABASE: <%= machineName %>_drupal
  volumes:
    - /data/<%= projectName %>_local/mysql:/var/lib/mysql
<% if (cacheInternal) { %>
<%- include cache.partial.yml -%>
<% } %>
www:
  container_name: <%= projectName %>_local_www
  image: <%= webImage %>
  environment:
    DNSDOCK_NAME: www
    DNSDOCK_IMAGE: <%= domain %>
    PHP_XDEBUG: "<%= debugMode %>"
    PHP_XHPROF: "<%= debugMode %>"
  links:
    - db<% if (cacheInternal) { %><%= cacheLink %><% } %>
  volumes:
    - .:/code/
    - ./build/html:/var/www/html
    - /data/<%= projectName %>_local/files:/var/www/html/sites/default/files
