db:
  container_name: <%= projectName %>_<%= environment %>_db
  extends:
    file: docker-compose.yml
    service: db
<% if (cacheInternal) { %>
cache:
  container_name: <%= projectName %>_<%= environment %>_cache
  extends:
    file: docker-compose.yml
    service: cache
<% } %>
www:
  container_name: <%= projectName %>_<%= environment %>_www
  image: <%= webImage %>
  environment:
    PHP_XDEBUG: "<%= debugMode %>"
    PHP_XHPROF: "<%= debugMode %>"
    VIRTUAL_HOST: <%= virtualHost %>
  links:
    - db<% if (cacheInternal) { %><%= cacheLink %><% } %>
  volumes:
    - .:/code/
    - ./build/html:/var/www/html
    - /data/<%= projectName %>/files:/var/www/html/sites/default/files
