##
# Operational services to run the application in your local environment.
##

# Database service
db:
  container_name: <%= machineName %>_local_db
  image: phase2/mariadb
  environment:
    DNSDOCK_NAME: db
    DNSDOCK_IMAGE: <%= domain %>
    MYSQL_DATABASE: <%= machineName %>_drupal
  volumes:
    - /data/<%= projectName %>_local/mysql:/var/lib/mysql
<% if (cache.external) { %>
# Application Cache service
cache:
  container_name: <%= projectName %>_local_cache
  image: <%= cache.image %>
  environment:
    DNSDOCK_NAME: cache
    DNSDOCK_IMAGE: <%= domain %>
<% } if (proxy.exists) { %>
# Reverse-proxy Cache service
proxy:
  container_name: <%= machineName %>_local_proxy
  image: phase2/varnish4
  environment:
    DNSDOCK_NAME: www
    DNSDOCK_IMAGE: <%= domain %>
    VARNISH_BACKEND_HOST: www
  links:
    - www
<% } %>
# Main Application service.
www:
  container_name: <%= machineName %>_local_www
  image: <%= app.image %>
  environment:
    DNSDOCK_NAME: <% if (proxy.exists) { %>app<% } else { %>www<% } %>
    DNSDOCK_IMAGE: <%= domain %>
    DOCROOT: /var/www/build/html
    PHP_XDEBUG: "<%= debugMode %>"
    PHP_XHPROF: "<%= debugMode %>"
  links:
    - db<% if (cache.external) { %><%= cache.docker.link %><% } %>
  volumes:
    - .:/var/www/
    - /data/<%= projectName %>_local/files:/var/www/build/html/sites/default/files
