db:
  container_name: <%= projectName %>_<%= environment %>_db
  extends:
    file: docker-compose.yml
    service: db
  volumes:
    - /data/<%= projectName %>_<%= environment %>/mysql:/var/lib/mysql
<% if (cacheExternal) { %>
cache:
  container_name: <%= projectName %>_<%= environment %>_cache
  extends:
    file: docker-compose.yml
    service: cache
<% } %>
www:
  container_name: <%= projectName %>_<%= environment %>_www
  image: <%= webImage %>
  environment:
    DOCROOT: /var/www/build/html
    PHP_XDEBUG: "<%= debugMode %>"
    PHP_XHPROF: "<%= debugMode %>"
    VIRTUAL_HOST: <%= virtualHost %>
  links:
    - db<% if (cacheExternal) { %><%= cacheLink %><% } %>
  volumes:
    - .:/var/www/
    - /data/<%= projectName %>_<%= environment %>/files:/var/www/build/html/sites/default/files
